### ISSUE TITLE
v0.9.7 Stage 4 testing PHA00001 does not see "recall" status of a batch with zero quantity

### ISSUE THREAD

**Issue by joaoluis-pdm** [PharmaLedger-IMI/fgt-workspace#104]
Email from Primoz at 28th July 2022 12:14, Subject: RE: Help on provisioning products and batches RE: PL - FGT - Stage 4 testing - Pfizer

> I did recall at the end, and saw the status at WHS screen:
 
![image](https://user-images.githubusercontent.com/77448470/181633639-87ff3afd-2e86-43b6-ae18-4d69d9841ddb.png)

> But not the PHA screen…:

![image](https://user-images.githubusercontent.com/77448470/181633702-f9625dfb-c6a6-4232-9580-edf3bb8c6bea.png)

**Comment by TiagoV-PDMFC** [comment]
I'm not sure this is a bug.... The notification algorithm is designed to message all participants with the product/batch combination in stock. If they do not have it in stock, they are not notified....

**Comment by joaoluis-pdm** [comment]
So, for now, we will classify this as a won't fix.
