### ISSUE TITLE
Error when performing a sale on dashboard

### ISSUE THREAD

**Issue by pccosta-pdm** [PharmaLedger-IMI/fgt-workspace#105]
Sale is not performing correctly.

Issues:
- A product just can be sold once;
- A sale with the same product (gtin+batch) with different serial number is not allowed;
- If a sale with the same product (gtin+batch) there is not enough quantity, an error will occur, as it only calculates one batch at a time (it always takes the first batch number from stock);
- Error product already sold: The "salesManager" is not checked (since we simulate a sale), so at each attempt of a new sale, it will always fetch the batches and serial numbers in sequence from the const DSU of products, ignoring that a serial number may have already been sold.

**Comment by joaoluis-pdm** [comment]
Released to TST on v0.10.4.
