### ISSUE TITLE
Security Risk - (4) MEDIUM - Missing_Encryption_of_Sensitive_Data 

### ISSUE THREAD

**Issue by TiagoV-PDMFC** [PharmaLedger-IMI/fgt-workspace#106]
From #94 

Deprecate the credentials file for the FGT API for an environment variable (with an eventual fallback to the credentials file)

**Comment by TiagoV-PDMFC** [comment]
We will start using an environment variable `FGT_API_CREDENTIALS` or something (that can be provided via Helm Charts or any other way), containing the JSON where the credentials are defined, and only if that environment variable does not exist, fallback to use the `credentials.json` file

**Comment by TiagoV-PDMFC** [comment]
Added an Environment variable `FGT_API_CREDENTIALS` that, if exists (accepts 'stringuified' JSON or JSON) will replace the call to read from the credentials file.

Extends to the fgt api and the `dashboard-wizard/credential-export.js` file call that exports the public credentials to the dashboard

**Comment by TiagoV-PDMFC** [comment]
testes in the dev environment. successfully overrides credentials

**Comment by joaoluis-pdm** [comment]
Released to TST on v0.10.4.
