### ISSUE TITLE
From #94 -  Description:A Content Security Policy is not explicitly defined within the web-application.

### ISSUE THREAD

**Issue by TiagoV-PDMFC** [PharmaLedger-IMI/fgt-workspace#110]
From #94 

CWE: [346](https://cwe.mitre.org/data/definitions/346.html)

(NEW) Description:A Content Security Policy is not explicitly defined within the web-application.

        res.statusCode = err.statusCode;
        res.write(JSON.stringify({
            status: err.statusCode,
            error: err.message,

    origin: [/fgt-api/middleware.js](https://github.com/PharmaLedger-IMI/fgt-workspace/blob/master/fgt-api/middleware.js#L8) - write line 8

**Comment by joaoluis-pdm** [comment]
Being a REST application/json server, adding a Content-Security-Policy should not be needed.

Nevertheless, if we add a Content-Security-Policy it does not seem to hurt the normal REST services functionality (according to https://stackoverflow.com/questions/37819249/what-does-it-mean-to-set-a-content-security-policy-on-response-to-a-non-html-req )
so it should be ok to set a CSP header, just to turn off the security scan vulnerability.

**Comment by joaoluis-pdm** [comment]
Released to TST on v0.10.4
