### ISSUE TITLE
Password should be invisible in logs

### ISSUE THREAD

**Issue by lukasosterheider** [PharmaLedger-IMI/fgt-workspace#115]
Currently, the logs are showing plain-text passwords.

Example:
"pass": {                                                                                                                                                  ││     "secret": "This1sSuchAS3curePassw0rd"                                                                                                                    ││   } 

Passwords and similar keys should be masked in logs.

**Comment by joaoluis-pdm** [comment]
A fix is pushed into master (see previous commit). Will be included in the next release v0.10.5 (or higher).
