### ISSUE TITLE
Implement a proper Navigation history tracker so we can have a functioning 'back button'

### ISSUE THREAD

**Issue by TiagoV-PDMFC** [PharmaLedger-IMI/fgt-workspace#16]

**Comment by TiagoV-PDMFC** [comment]
in  pdm-dsu-toolkit's HomeController implement a 'goBack' mechanism with proper history tracking.

Right now the in-app navigation is handled in the with the 'EVENT_ION_TABS_WILL_CHANGE' and 'EVENT_NAVIGATE_TAB' handlers of that controller.

My suggestion is that this controller also listens for a 'back' event that will then send navigation to the previous navigation request, with the same properties that had been originally passed.

As a nice to have, a way to manage to get a label out of each page would be nice

**Comment by TiagoV-PDMFC** [comment]
History mechanism seems to be working well. I would however like to see it completely separated from other webcomponents.

For that effect I propose you create a new 'BackButton' component that encapsulates all the logic. Therefore no other components ever has to worry about this functionality.

Remember to do it in a fully configurable fashion (all ion-button props must be replicated)

**Comment by pccosta-pdm** [comment]
back-button as a component created and ready for review
