### ISSUE TITLE
Status Update Refactor

### ISSUE THREAD

**Issue by TiagoV-PDMFC** [PharmaLedger-IMI/fgt-workspace#22]
The status-updater webcomponent at this time only allows to update status (both for the shipments and orders). No comments are allowed.

Because we need comments some of the status updates, eg when updating to 'delivered', comments should be added on delivery, where there problems, damages, etc;

Implement a new version of this component where when you click a status update, a 'drawer' opens allowing to input comments before submitting.

All the implementation can be made on the status-updater component, but i would advide on creating a 'status-update-button' component that would handle all the drawer logic and submit the update to the status-updater.

A refactor on the Status service and Model object (and inherently the other Model Objects that have status and their managers - shipment, order) would be required.

While I tagged this as a 'good first issue', its a good first issue for someone already familiarized with our SSApp Architecture, and willing to go further into the OpenDSU framework

**Comment by pccosta-pdm** [comment]
Ready for review
