### ISSUE TITLE
(low pri) - Dashboard - implement a proper dashboard

### ISSUE THREAD

**Issue by TiagoV-PDMFC** [PharmaLedger-IMI/fgt-workspace#32]
Now we have all functionality and are able to gather metrics, use the graph components from acdc to display several metrics on products/batches shipments/orders

**Comment by TiagoV-PDMFC** [comment]
It would be nice to have a really nice dashboard implementation:
 - add/remove graphics;
 - Rezize graphs;
 - etc (there are several small dashboard libraries that manage this we can fall back on);

The priority is however:
 - Create a general, managed, configurable Graph component;
 - Display on the dashboard for MAH:
   - Most sold product (overall, or by wholesaler);
   - Most stock of product X (product should be configurable);
   - Pending shipments (by product, receiver, etc);

While you should, on an initial iteration, hardcode these graphs, ideally we should develop some kind of all powerfull component that enables easy configuration of these queries by the user. If we join this with a dashboard configuration capability, then we have a fully configurable dashboard for users (which is what they want)

**Comment by pccosta-pdm** [comment]
some notes:
- when the browser windows is resized, the chart click event send the data of previous state. It's needed listen the window resizing to render chart again to update the chart metadata (location of click event, which bar was clicked, etc.)
- the receipt communication (when a sale is performed) between PHA and MAH, are not occurring properly. On the MAH side, the message cannot be read
![image](https://user-images.githubusercontent.com/81983397/142006253-2a1c4758-78a9-4c0a-84d8-f798a0219cb0.png)

**Comment by pccosta-pdm** [comment]
- show loading when chart is updating
- add filters and clear filter (for now, the only filter is when click on "shipments chart", to back to initial visualization, it's needed to click on update button)
- fix the above issues

**Comment by TiagoV-PDMFC** [comment]
The bug mentioned above is now registered (and diagnosed in #52 )

the code looks good. as a comment, all string should come from translate.json file, including:

`
            const statusDictionary = {
                created: 'Created',
                hold: 'on Hold',
                pickup: 'for Pickup',
                transit: 'in Transit',
                delivered: 'Delivered',
                received: 'Pending Conf.',
                recall: 'Recall'
            }`

so they'll be properly rendered with different languages

**Comment by TiagoV-PDMFC** [comment]
Apart from that, this is very good, especially for now.

this issue will not be closed because improvements will have to be made:
 - configurable dashboard (user can add remove graphics, stores for next session)
 - integrate colors with ionic colors (so they react when we change the theme and you dont need to pass background color configs and border and all that (or at least have them has fallback);
 - configurable graphics: given the proper manager, the property you want to query, time intervals, chart type, select participants, refresh rates, etc, so these update methods can be somehow automatized

**Comment by TiagoV-PDMFC** [comment]
The loading should be easy enough to implement.... just while there is no data show one of the multi-spinner component options

**Comment by TiagoV-PDMFC** [comment]
regarding the rezize issue, cant you do it on the controller? should be asy enough if its just calling some methods. i do it in the home controller or in the layout component if im not mistaken

**Comment by pccosta-pdm** [comment]
1. configurable dashboard to user:
	- add and remove graphics
	- select to show or not the data source table (and select number of rows to show, be able to ordering, table position)
	- select the number of bars on graph
	- filter by different options (check the no.4 below)
2. store the chart config between rendering and sessions
3.  integrate colors with ionic colors
4. configurable graphics: given the proper manager, the property you want to query, time intervals, chart type, select participants, refresh rates, etc, so these update methods can be somehow automatized
	- p.s.: the loading indicator is inside graph component, but the logic of the query is on controller. This prevents that when manual update occurs, the component cannot capture this "streaming" from controller, with updated above, this issue can be solve. _previous attempts: by javascript DOM disabling/enabling the loading spinner / stencil lifecycle without the potential of getting components stuck in an infinite re-render loop_
5. for better understanding of user, and for a integrity purpose, my suggestion is to have a "main" filter with period of time (year, month), when this filter is changed, all charts are updated with the selected time interval, instead of control in each chart.

**Comment by pccosta-pdm** [comment]
issue still open for future enhancement

**Comment by TiagoV-PDMFC** [comment]
This issue is no longer relevant in the scope of the REST API and issue #62
