### ISSUE TITLE
Implement Partner Stock Control

### ISSUE THREAD

**Issue by TiagoV-PDMFC** [PharmaLedger-IMI/fgt-workspace#38]
MAH, via the shipinglines/receipts, can control the stock of every partner.

Step 1: Implement this feature:
Step2: Use the graph component previously developed for the ac use case to display information that information on the dashboard

**Comment by TiagoV-PDMFC** [comment]
related to #4

**Comment by pccosta-pdm** [comment]
implemented with #40
