### ISSUE TITLE
Refactor Status Updater Object

### ISSUE THREAD

**Issue by TiagoV-PDMFC** [PharmaLedger-IMI/fgt-workspace#41]
Refactor the status updater Web Component to display all history of the status

**Comment by pccosta-pdm** [comment]
> 1. When statuses are updated, some may not have extraInfo but will be inserted into the array as an "ID TIMESTAMP" element**
> **A: It is valid, however, when integration with partners, the requester's ERP/Software will only receive the status, and to solve it on current application, a much more complex object is needed, for now it's important just to show the funcionallity**
> 2. Validation of status change is external to object creation/insertion/update (method status.validate(newStatus) => {...}), that is, when status is updated by IssueOrder.updatedFromShipment, validation does not occur, assuming that what is received is the truth, a validation could be done (but still the validation would not be in the insert/update to guarantee the integrity).
> **A: create an issue for that**
> 3. It is currently allowed to create new shipments from the same order (even if it has already been accepted), so the update history can get "dirty", e.g:
> 
> * MAH history: created -> pickup -> (create a new shipment for the same order)
> * WH history: created -> acknowledged -> pickup -> acknowledged
> **A: This problem is to be solved by order requester, the wallet application is able to solve the logic of Shipment. The logic of Order is the responsibility of the issuer (which will probably be controlled by ERP). So...of our point, it's not worth apply or define this logic** 
> -----
> ** on the frontend, to use the status log and extraInfo, it's required to "sanitize" the message (e.g. removing ID and TIMESTAMP), something that also occurs when a message is received by IssueOrder.updateFromShipment, as it receives the Shipment status from (for example) MAH, so the extraInfo refers to ID_MAH+TIMESTAMP, but when it is inserted in the Order, it must be inserted as ID_WHOLESALER+TIMESTAMP, producing code replication, or in the future, performance issues.

**Comment by TiagoV-PDMFC** [comment]
well done.
