### ISSUE TITLE
Properly Test StockManager and its manage* methods

### ISSUE THREAD

**Issue by TiagoV-PDMFC** [PharmaLedger-IMI/fgt-workspace#46]
In the UI ate least, the stock is not being properly updated upon shipment confirmation.

This reverts to the methods Manager and ManageAll (and i guess update as well) but also the update method in issuedOrderManager.

Please perform unit tests confirming if the stocks are properly handled when these events happen

**Comment by TiagoV-PDMFC** [comment]
If that doesnt work, debug the shit out of it in the UI (you stop at a breakpoint after the supposed stock update has been commited to the db and go to dossier explroer to inspec it)

**Comment by TiagoV-PDMFC** [comment]
relates to #29

**Comment by TiagoV-PDMFC** [comment]
Please also update the stock components to filter out empty batches

**Comment by TiagoV-PDMFC** [comment]
Stock operations are still not working properly, as now seem to have induced a quantity bug in the shipment logic.

ex: did a small order from a pharmacy to wholesaler (ex 6 of product X when the wholesaler has 80+ on stock);

After accepting the order, the shipment is created with all the stock of the wholesaler, not just the 6 requested.

When in the pharmacy, after all the shipment status updates have been done, the quantity added is the full amount of the wholesaler stock, not what was ordered, and that is only visible when we 'reboot' the application.

Also, the updates to the stock component induced some kind of recursive bug (that is very visible on the console and cannot happen.... break the application is some cases)

**Comment by VNogueira91** [comment]
Work around the issue was made, to fully fix the issue wholesaler ssaap and pharmacy ssaap should have their own participant manager that creates the stockmanager with serialization as false.

**Comment by TiagoV-PDMFC** [comment]
Stock operations are now updating properly. well done
