### ISSUE TITLE
Message Manager - test

### ISSUE THREAD

**Issue by TiagoV-PDMFC** [PharmaLedger-IMI/fgt-workspace#50]
The message manager, that handles all communication, has a defect:
if it receives a message for a given api, before the proper manager registers its listener, the query to find all unhandled messages for that api is always returning 0 results (in the UI at least).

This might be a concurrency issue (when the query is done, is hasnt finished inserting the data, so it cant be retrieved).
Or might just be a Tiago induced Bug.

Please test this specific functionality and propose a fix for it

**Comment by TiagoV-PDMFC** [comment]
@VNogueira91 has this been fixed?

**Comment by VNogueira91** [comment]
After reviewing the code present in refs50_MessageManageFix and merging master into it the proposed solution on that branch had alot of bugs and did not work a new branch was created taking the master as base and a new proposed solution was created. To review this new proposed solution check refs50_message branch.

**Comment by VNogueira91** [comment]
The proposed solution starts the receiving messages process after all listeners are registered.
