### ISSUE TITLE
Portential problem on concurrent stock updates during npm run environment-test

### ISSUE THREAD

**Issue by joaoluis-pdm** [PharmaLedger-IMI/fgt-workspace#55]
How to reproduce at ac5657d7

```
npm run environment-test >log4.txt 2>&1
```

Consider the 1st MAH:
It has 4 Received Orders. Only the 1st is confirmed (and all 4 should be confirmed).
![image](https://user-images.githubusercontent.com/77448470/144606672-2d33d4c7-82ae-45db-8b8a-d2d54714d802.png)

It has only onle shipment. It should have 4 shipments (one for each order)
![image](https://user-images.githubusercontent.com/77448470/144606759-0dc5209d-553f-4e20-b049-9ca2f35260a3.png)

Lets add some console.log at 06e3e2b3b724f4005f6e561cb752235cb59a152b
and lets look at log4.txt and see what happens for orderId=1638533252330
```
...
going to dbAction orderId=1638533252330
dbAction orderId=1638533252330
...

```

It seems to be locked in self.beginBatch() (calls DBLock.beginBatch(tableName) forever...

**Comment by joaoluis-pdm** [comment]
Adding more logs c6ecfd1 
```
npm run clean ; npm run build-all
npm run environment-test >log5.txt 2>&1
```

Troublesome orderId=1638537518686
log5.txt
```
dbAction orderId=1638537518686
DBLock.beginBatch(issuedShipments)
_storage.beginBatch() start
_storage.beginBatch() done
beginBatch ok for orderId=1638537518686
DBLock.beginBatch(stock)
...
```

Nothing evers mention 1638537518686 again.
Did it block at gtinIterator?

**Comment by joaoluis-pdm** [comment]
More console.log on 5ee1649 
Troublesome orderId=1638544778998
log7.txt
```
...

Stock confirmed for order: Order {
  orderId: 1638544778998,
...
dbAction orderId=1638544778998
DBLock.beginBatch(issuedShipments)
_storage.beginBatch() start
_storage.beginBatch() done
beginBatch ok for orderId=1638544778998
gtinIterator ongoing for orderId=1638544778998 [ '08470007909231', '05415062336861', '05415062336861' ]
manageAll start
manageAll(08470007909231,...) dbAction start
DBLock.beginBatch(stock)
...
...
gtinIterator ongoing for orderId=1638544778998 [ '05415062336861', '05415062336861' ]
...
Going to delete messages's record {
  api: 'shipmentLines',
  message: '["29fgyfTQXJmJNnNBAY4wyGdF59upK4uXGM3jtcYhxXY2Ta166iPB2GSgy97EfWw3ZtQYkU9nbuuNPE3Xkf9RRadwXCjWAVD","65FmT6jYpmQXh9ETs68RdMxy7LL7pkErsn2fYKXpd3CuEUf6jApbCcPGbEyzqNtPtLnnjLEgF2uoYVkNCTCkXRUVL9fwCmjd"]',
  key: '1638544781162'
}
OrderStatus DSU (ssi:seed:traceability:AhVy5uE7aGaM1WPLhz8E6amrfL7kSRZ5i5yeA88hm7o1::v0) mounted at '/status'
Error processing Api receivedOrders Could not update Stock for orderId=1638544778998
...
```
I don't understand the last error message!

**Comment by joaoluis-pdm** [comment]
Moving to branch refs55_concurrency

**Comment by joaoluis-pdm** [comment]
The 2 commits above revert the added console.logs from master...

**Comment by joaoluis-pdm** [comment]
More console.log on 9f82fe1 

The error now presented is:
```
...
Error processing Api receivedOrders Could not update Stock for orderId=1638550069486 because of Could not perform manage all on Stock beacause Illegal quantity. Not enough Stock. requested -164 of 36
...
```

**Comment by joaoluis-pdm** [comment]
Could just be lack of stock. (The https://github.com/PharmaLedger-IMI/fgt-workspace//blob/865ab3e61e54d4a78b67702f296dfac46b0639e9/bin/environment/listeners/orderListener.js does not have to be smart enough to select quantities from different batches... or does it ?)

**Comment by TiagoV-PDMFC** [comment]
Was diagnosed to lack of stock
