### ISSUE TITLE
Product manager page is not showing/updating with new info

### ISSUE THREAD

**Issue by pccosta-pdm** [PharmaLedger-IMI/fgt-workspace#57]
When access the product manager page a query is not performed (it doesn't render), so new information is not shown.

e.g.: products -> manage product -> add batch -> go back -> manage product
1. on products page, a query is always performed
![image](https://user-images.githubusercontent.com/81983397/146357191-6fe0f8de-3515-413b-af7d-d35b0796e5cd.png)
2. on manage product
![image](https://user-images.githubusercontent.com/81983397/146357291-25b4200a-a964-4514-87ab-0042d549fb22.png)

**Comment by pccosta-pdm** [comment]
There is a issue with "getPage" on main manager:
- Query by keyword uses the manager/table indexes and perform a search for each index

There is a issue is when a composite key it's needed.

e.g.: Batch - to found a batch properly it's needed the GTIN and BatchNumber. So in the ProductManage that list all batches of a product, when table loads or query by search bar, it's needed to include GTIN (as a mandatory field to ensure data integrity) + keyword query.

**Comment by pccosta-pdm** [comment]
test a different component update with state and force render, the last one was to put: 
`self.element.querySelector('pdm-ion-table').refresh();`
on ProductController, but another issue appear: 
![image](https://user-images.githubusercontent.com/81983397/148959908-7b29f895-7a12-4f33-ac9b-f5547cd7a3c5.png)
The problem seems to be that the data between components are not being update or a specific condition do a different query, the correct screen is:
![image](https://user-images.githubusercontent.com/81983397/148960121-7eeaf41e-aa6d-4cf6-b87f-e059d7262b87.png)

The query is not the problem, because when change the page (e.g. 1 to 2), the data that belongs that GTIN is correctly queried and loaded.

**Comment by pccosta-pdm** [comment]
the problem is that the props is not received in a sync way (even though the parent component provides this synchronously), and added a state to update was sticking it in a infinite loop.

**Comment by joaoluis-pdm** [comment]
There is no UI anymore, so this issue is now rejected.
