### ISSUE TITLE
When scan a product, the page header disappears

### ISSUE THREAD

**Issue by pccosta-pdm** [PharmaLedger-IMI/fgt-workspace#58]
**Before scan:**
![image](https://user-images.githubusercontent.com/81983397/147679749-0f72025e-87e6-4424-b521-e9cf70a65a76.png)

**After click on scan button:**
![image](https://user-images.githubusercontent.com/81983397/147679546-c2fa471e-bf80-46e6-a85a-8722f22d5f19.png)

**After leave it:**
![image](https://user-images.githubusercontent.com/81983397/147679624-b17f5d3c-5410-4f80-af71-dd9e20c25afa.png)

**Comment by joaoluis-pdm** [comment]
There is no UI anymore. So this is rejected.
