### ISSUE TITLE
Partner Onboarding (Continuation)

### ISSUE THREAD

**Issue by TiagoV-PDMFC** [PharmaLedger-IMI/fgt-workspace#60]
Following the conclusion of #43, we now need to create the deployment script to replicate the environment.

To this effect, we need a big docker compose file to raise all the environments at once:
- fgt workspace (with or without blockchain, not relevant right now): Will expose the OpenDSU Api to the 'traceability' domain;
- each MAH/WHS/PHA will have to be a docker file (clone fgt, install, server, build-all), the credentials and startup (decide which api should be run for each container) should be set up by docker compose and made to be executed after the whole environment is set up.
- DNS mapping for all participant apis (so we can use postman from outside the server, and the partners can interact with it)

**Comment by TiagoV-PDMFC** [comment]
I would argue that it should go like this:
- Step one: mimick fgt's docker file for the Traceability environment;
- Step two: create a docker file for MAH/WHS/PHA API;
- Connect the two 'manually' (launch a docker, launch another and have them communicate)
- assemble the docker compose, using all the files and configuration above, to incrementally add more participants (mahs, whs, etc) and have dns for all of them

**Comment by TiagoV-PDMFC** [comment]
Partner onboarding (REST API and ERP Integration Possibilities) has been deployed in v0.8.0. Improvements will be included in new issues

**Comment by joaoluis-pdm** [comment]
bootCompose on fgt-dev-pl is now frequently presenting errors on starting up the last PHA participants.
```txt
...
WARNING: Image for service pha-2 was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating fgt-workspace     ... done
Creating traefik           ... done
Creating traefik-logrotate ... done
Creating mah-gsk           ... done
Creating mah-msd           ... done
Creating mah-roche         ... done
Creating mah-sanofi        ... done
Creating mah-bayer         ... done
Creating mah-novo-nordisk  ... done
Creating mah-pfizer        ... done
Creating mah-takeda        ... done
Creating whs-zuellig       ... done
Creating whs-takeda        ... done
Creating whs2              ... done
Creating whs1              ... done
Creating pha2              ... done

 

ERROR: for pha-1  Container "6652d7341057" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

Let's try to extend the health-check periodicity a little bit...

**Comment by joaoluis-pdm** [comment]
The healthcare interval is not the problem. The problem seems to be that all WHSs are unhealthy... (and that could be related to #113, or #117 instead).
