### ISSUE TITLE
Incoming simple shipments' id is the same the as set by the Sender. They should be unique

### ISSUE THREAD

**Issue by TiagoV-PDMFC** [PharmaLedger-IMI/fgt-workspace#61]
To avoid conflicts (even if unprobable) add a sender prefix to incoming shipments ID's

**Comment by TiagoV-PDMFC** [comment]
Looks good, but add a separator character between the sender id and the shipment id. It's a bit redundant, but if anyone ever needs to parse it, is makes that easy. after that you can close the issue

**Comment by pccosta-pdm** [comment]
fix on https://github.com/PharmaLedger-IMI/fgt-workspace/commit/d8ae19506fd64294442bf069e47e205fa4915c2a
