### ISSUE TITLE
General CSS problems - specific fgt-mah-ssapp/code/pages/modals/registrationModal.html may overflow screen size without scroll

### ISSUE THREAD

**Issue by joaoluis-pdm** [PharmaLedger-IMI/fgt-workspace#9]
fgt-mah-ssapp/code/pages/modals/registrationModal.html may overflow screen size without scroll
![image](https://user-images.githubusercontent.com/77448470/110127861-066d0b80-7dbe-11eb-8513-19e824814395.png)
There is no scrollbar, and the fields at the bottom are not accessible (unless browser zoom-out is used).

How to solve this ? By CSS ?
https://privatesky.xyz/?Cardinal/components/psk-modal
does not seem to help.

**Comment by TiagoV-PDMFC** [comment]
Closed in issue #13
